spring: 
    datasource:
        url: jdbc:mysql://192.168.99.100:3306/updp?Unicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
        username: root
        password: 1
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        maxActive: 20
        minIdle: 5
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false        
    jpa:
        database : MYSQL
        #show-sql : true
        hibernate:
          ddl-auto : update
          naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
        properties:
              hibernate:
                  dialect : org.hibernate.dialect.MySQL5Dialect
                  hbm2ddl: auto:validate
                  ddl-auto: update  
pagehelper: 
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql